STORY_FUNCTION_ENUM = [
    "hook",
    "problem",
    "turn",
    "progression",
    "climax",
    "cta",
    "resolution",
]

CAMERA_ANGLE_ENUM = [
    "eye_level",
    "close_angle",
    "over_shoulder",
    "high_angle",
    "low_angle",
    "pov",
]

CAMERA_MOVEMENT_ENUM = [
    "static",
    "rapid_cut",
    "graphic_motion",
    "tracking",
    "push_in",
    "pull_out",
    "pan",
    "slow_motion",
    "handheld",
]

TRANSITION_ENUM = [
    "cold_open",
    "hard_cut",
    "match_cut",
    "scene_cut",
    "look_reveal_cut",
    "location_cut",
    "linger_cut",
    "hold_on_end",
    "fade_in",
    "fade_out",
    "dissolve",
]

ASSET_BIBLE_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "asset_bible",
    "type": "object",
    "required": [
        "schema_version",
        "project_title",
        "host_identity",
        "look_definitions",
        "locations",
        "global_visual_style",
        "negative_drift_rules",
        "climax_protection",
    ],
    "properties": {
        "schema_version": {"type": "string"},
        "project_title": {"type": "string"},
        "source_storyboard_stage": {"type": "string"},
        "host_identity": {
            "type": "object",
            "required": ["host_id", "name", "role", "identity_notes", "continuity_notes"],
            "properties": {
                "host_id": {"type": "string"},
                "name": {"type": "string"},
                "role": {"type": "string"},
                "identity_notes": {"type": "array", "items": {"type": "string"}},
                "continuity_notes": {"type": "array", "items": {"type": "string"}},
            },
        },
        "look_definitions": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "look_id",
                    "name",
                    "style",
                    "hero_items",
                    "accessories",
                    "color_palette",
                    "mood",
                    "continuity_rules",
                ],
                "properties": {
                    "look_id": {"type": "string"},
                    "name": {"type": "string"},
                    "style": {"type": "string"},
                    "hero_items": {"type": "array", "items": {"type": "string"}},
                    "accessories": {"type": "array", "items": {"type": "string"}},
                    "color_palette": {"type": "array", "items": {"type": "string"}},
                    "mood": {"type": "string"},
                    "continuity_rules": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
        "locations": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "location_id",
                    "name",
                    "world_type",
                    "signature_elements",
                    "mood",
                    "continuity_rules",
                ],
                "properties": {
                    "location_id": {"type": "string"},
                    "name": {"type": "string"},
                    "world_type": {"type": "string"},
                    "signature_elements": {"type": "array", "items": {"type": "string"}},
                    "mood": {"type": "string"},
                    "continuity_rules": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
        "global_visual_style": {
            "type": "object",
            "required": ["format", "lighting", "color_strategy", "lens_language", "motion_language"],
            "properties": {
                "format": {"type": "string"},
                "lighting": {"type": "string"},
                "color_strategy": {"type": "string"},
                "lens_language": {"type": "string"},
                "motion_language": {"type": "string"},
                "texture_bias": {"type": "string"},
            },
        },
        "negative_drift_rules": {"type": "array", "items": {"type": "string"}},
        "climax_protection": {
            "type": "object",
            "required": ["protected_story_beats", "protected_looks", "protected_locations", "protected_shots"],
            "properties": {
                "protected_story_beats": {"type": "array", "items": {"type": "string"}},
                "protected_looks": {"type": "array", "items": {"type": "string"}},
                "protected_locations": {"type": "array", "items": {"type": "string"}},
                "protected_shots": {"type": "array", "items": {"type": "string"}},
            },
        },
    },
}

SHOT_SPEC_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "shot_spec",
    "type": "object",
    "required": ["schema_version", "project_title", "sequences", "shots"],
    "properties": {
        "schema_version": {"type": "string"},
        "project_title": {"type": "string"},
        "sequences": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["sequence_id", "title", "story_change", "scenes"],
                "properties": {
                    "sequence_id": {"type": "string"},
                    "title": {"type": "string"},
                    "story_change": {"type": "string"},
                    "scenes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["scene_id", "title", "purpose", "shots"],
                            "properties": {
                                "scene_id": {"type": "string"},
                                "title": {"type": "string"},
                                "purpose": {"type": "string"},
                                "location_ref": {"type": "string"},
                                "look_ref": {"type": "string"},
                                "duration_sec": {"type": "number"},
                                "shot_count": {"type": "integer"},
                                "shots": {"type": "array", "items": {"type": "string"}},
                            },
                        },
                    },
                    "duration_sec": {"type": "number"},
                },
            },
        },
        "shots": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "shot_id",
                    "sequence_id",
                    "scene_id",
                    "purpose",
                    "story_function",
                    "subject",
                    "action",
                    "framing",
                    "camera_angle",
                    "camera_movement",
                    "duration_sec",
                    "emotion",
                    "continuity_anchor",
                    "prev_shot_id",
                    "next_shot_id",
                    "transition_in",
                    "transition_out",
                    "look_ref",
                    "location_ref",
                    "audio_cue",
                    "climax_weight",
                    "climax_protected",
                    "prompt_intent",
                ],
                "properties": {
                    "shot_id": {"type": "string"},
                    "sequence_id": {"type": "string"},
                    "scene_id": {"type": "string"},
                    "sequence_order": {"type": "integer"},
                    "scene_order": {"type": "integer"},
                    "shot_order": {"type": "integer"},
                    "purpose": {"type": "string"},
                    "story_function": {"type": "string", "enum": STORY_FUNCTION_ENUM},
                    "subject": {"type": "string"},
                    "action": {"type": "string"},
                    "framing": {"type": "string"},
                    "camera_angle": {"type": "string", "enum": CAMERA_ANGLE_ENUM},
                    "camera_movement": {"type": "string", "enum": CAMERA_MOVEMENT_ENUM},
                    "duration_sec": {"type": "number"},
                    "emotion": {"type": "string"},
                    "continuity_anchor": {"type": "string"},
                    "prev_shot_id": {"type": "string"},
                    "next_shot_id": {"type": "string"},
                    "continuity_refs": {"type": "array", "items": {"type": "string"}},
                    "transition_in": {"type": "string", "enum": TRANSITION_ENUM},
                    "transition_out": {"type": "string", "enum": TRANSITION_ENUM},
                    "look_ref": {"type": "string"},
                    "location_ref": {"type": "string"},
                    "audio_cue": {"type": "string"},
                    "climax_weight": {"type": "number"},
                    "climax_protected": {"type": "boolean"},
                    "prompt_intent": {"type": "string"},
                },
            },
        },
    },
}

PROMPT_PACK_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "prompt_pack",
    "type": "object",
    "required": ["schema_version", "project_title", "prompts"],
    "properties": {
        "schema_version": {"type": "string"},
        "project_title": {"type": "string"},
        "prompts": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "shot_id",
                    "keyframe_prompt",
                    "motion_prompt",
                    "negative_prompt",
                    "continuity_note",
                    "edit_note",
                ],
                "properties": {
                    "shot_id": {"type": "string"},
                    "keyframe_prompt": {"type": "string"},
                    "motion_prompt": {"type": "string"},
                    "negative_prompt": {"type": "string"},
                    "continuity_note": {"type": "string"},
                    "edit_note": {"type": "string"},
                },
            },
        },
    },
}
